spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartqa
    username: pguser
    password: pgpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
